---
# tasks file for prepare_dev_tools
- name: manage common packages redhat
  become: yes
  when: ansible_facts.os_family == 'RedHat'
  tags: system-packages
  block:
    - name: Install RPM packages
      package:
        name: "{{ (redhat_pkg_install | join(' ')).split() }}"
        state: present
        update_cache: yes
    - name: remove extra  RPM package
      when: redhat_pkg_remove_extra | bool
      package:
        name: "{{ (redhat_pkg_remove_extra | join(' ')).split() }}"
        state: absent
    - name: Install extra  RPM packages
      when: redhat_pkg_install_extra | bool
      package:
        name: "{{ (redhat_pkg_install_extra | join(' ')).split() }}"
        state: present
        update_cache: yes
