---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

ConfigMapGenerator:
- name: service-account-data
  envs:
  -  account.env
generatorOptions:
  disableNameSuffixHash: true

resources:
 - user.yaml
 - cluster_role_binding.yaml
 - service_token_secret.yaml

replacements:
- source:
    fieldPath: data.name
    kind: ConfigMap
    name: service-account-data
    version: v1
  targets:
  - fieldPaths:
    - metadata.name
    select:
      kind: ServiceAccount
  - fieldPaths:
    - metadata.name
    - subjects.[kind=ServiceAccount].name
    select:
      kind: ClusterRoleBinding
  - fieldPaths:
    - metadata.name
    - metadata.annotations.[kubernetes.io/service-account.name]
    select:
      kind: Secret
      name: service_account_token
- source:
    fieldPath: data.cluster_role
    kind: ConfigMap
    name: service-account-data
    version: v1
  targets:
  - fieldPaths:
    - roleRef.name
    select:
      kind: ClusterRoleBinding
