---
dependency:
  name: galaxy
driver:
  name: containers
platforms:
  - name: controller
    image: quay.io/smooney/podman-init:latest
    privileged: true
    network: oks
    systemd: true
    pre_build_image: true
    override_command: false
    published_ports:
      - 0.0.0.0:55000:22/tcp
    cgroups: no-conmon
    volumes:
     - /dev:/dev
    tty: true
  - name: compute-1
    image: quay.io/smooney/podman-init:latest
    privileged: true
    network: oks
    systemd: true
    pre_build_image: true
    override_command: false
    published_ports:
      - 0.0.0.0:55001:22/tcp
provisioner:
  name: ansible
  inventory:
    host_vars:
      # setting for the platform instance named 'instance'
      controller:
        ansible_user: stack
      compute-1:
        ansible_user: stack
  env:
    ANSIBLE_ROLES_PATH: "${ANSIBLE_ROLES_PATH}:../../submodule:../../ansible/roles"
verifier:
  name: ansible
