---
# tasks file for print_debug_ip
- name: register host ip for ssh login
  tags : ip
  shell: "cat /etc/hosts | awk '/{{ansible_host}}/ {print $1}'"
  register: ip_addr

- name: display host
  tags : ip
  debug:
    var: ansible_host

- name: display host ip for ssh login
  tags : ip
  debug:
    var: ip_addr.stdout